title: "Taylor Swift — Her Complete Eras"
description: "A fan-made website celebrating Taylor Swift’s music, eras, and artistry."
baseurl: "/Taylor_Swift_fanpage" 
url: "https://lola81tlr.github.io/Taylor_Swift_fanpage/" 

theme: minima 

markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: "index.md" 
    values:
      layout: "default"
      font_family: "'Georgia', serif"
      background_color: "#D9BB9B"

sass:
  style: compressed
